name: Test Build

on:
  pull_request:
    branches:
      - '*'

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-xcproject:
    name: Build GitSpace!
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - name: Xcode 15.0 선택
        run: sudo xcode-select -s /Applications/Xcode_15.0.app
      - name: Build
        run: |
          xcodebuild build -project GitSpace.xcodeproj -scheme GitSpace -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=latest'
          cd ~/Library/Developer/Xcode/DerivedData/GitSpace-*/Build/Products/Debug-iphonesimulator/GitSpace.app
  
  # test-package:
  #   name: Test GitSpace?
  #   runs-on: macos-13
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Xcode 15.0 선택
  #       run: sudo xcode-select -s /Applications/Xcode_15.0.app
  #     - name: Test Build
  #       run: |
  #         cd GitSpace-test
  #         xcodebuild test -scheme FetcherTests -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=latest'
